### DISCUSSION TITLE
How does HA control the Powerwall?

### DISCUSSION THREAD

**Discussion by wyx087** [alandtse/tesla#1017] [Q&A] [answered]
Can I ask a few questions whilst deciding on my home battery install? 

Powerwall 3 looks like a great product, Tesla's expertise on BMS and its thermal management make it a great candidate for my install outdoors. However, looking into Tesla app -> Discover -> Powerwall demo there is so little configurable settings it doesn't feel like I'm buying a battery I can control and automate. 

Here's a starter list of controls I need for my home battery, can I do this in HA via this Tesla custom integration? 
1. Force battery to stop load balancing and go idle/inactive/hold. 
2. Force battery to start charging on my command at power level of my choosing 
3. Force battery to discharge on my command at power level of my choosing 
4. Set overnight charge limit to leave space for solar excess. 

The controls exposed by this Tesla custom integration is bizarre, I can't wrap my head around what each one does and how to achieve what I want to do. 

My other cheaper battery candidate can easily do all those with local control (Tesla control is via cloud isn't it?). But it need some weather shielding and people report BMS isn't good at reporting SoC. So as a physical product it's worse. 

Also, when you open the Tesla app to look at Powerwall, presumably it opens to your car and as a result the car will wake up? 

Thanks very much

**Comment by skipishere** [comment, marked as answer]
I have a Powerwall 2 (so this may not be 100% correct for Powerwall 3) and am using the unofficial API:
1) You can change the battery from Time-Based control to Self-Powered, in this case with Self powered you won't draw from the grid unless you hit your reserve level.
2) ~ish you can set the reserve level which can force the battery to charge if set to Time-Based & Grid charging it might charge but it tries to be clever and charge up depending on your usage/solar generation (if applicable) which may not be what you want. I have an automation that will bump up the reserve level to 5% less than a set charge level that will swap the battery from Grid charging `Yes` to `No`. This is more tricking the powerwall then actually getting it to charge.
3) No~ish. If you have the rates set so the battery thinks it's worth discharging & you have Time-Based then it may discharge, but there are times when the powerwall tries to be smart and won't discharge due to usage it thinks you might use.
4) Yes - kind of explained in point 2

In terms of Local/Cloud, the official plugin with Home Assistant is Local but there are many things that (currently) can't be controlled locally (😭) which is one of the reasons this plugin exists (which uses cloud)

This is my dashboard with 2 helpers and 2 binary sensors (to make things easier)
![image](https://github.com/alandtse/tesla/assets/26724777/5d556e98-f0e0-4df0-ae45-8d9e7ad4ef78)

```YAML
    charge_house_battery:
      friendly_name: "Charge Powerwall from grid"
      value_template: >-
        {{ int(states('sensor.powerwall_charge')) < int(states('input_number.powerwall_charge_threshold'))
        and states('select.electric_import') == 'Off-Peak' }}
      icon_template: >-
        {% if is_state('binary_sensor.charge_house_battery','on') %} mdi:transmission-tower-import
        {% else %} mdi:transmission-tower-off
        {% endif %}
        
    discharge_house_battery:
      friendly_name: "Discharge Powerwall to grid"
      value_template: >-
        {{ int(states('sensor.powerwall_charge')) > int(states('input_number.powerwall_discharge_threshold'))
        and states('select.electric_import') == 'Peak' }}
      icon_template: >-
        {% if is_state('binary_sensor.discharge_house_battery','on') %} mdi:transmission-tower-export
        {% else %} mdi:transmission-tower-off
        {% endif %}
```

I'm on a time of use tariff so also have a seperate automation that changes the `electric_export` and `electric_import` based on time (which is further complicated by occasionally having Free Power time slots and Saving Sessions, which I've not included here)

Import Automation:
```YAML
alias: Powerwall Import
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.charge_house_battery
    id: start
    from: null
    to: "on"
  - platform: state
    entity_id:
      - select.electric_import
    from: Off-Peak
    id: stop
  - platform: state
    entity_id:
      - binary_sensor.charge_house_battery
    from: null
    to: "off"
    id: stop
  - platform: state
    entity_id:
      - select.electric_import
    from: Free
    id: stop
    to: Mid-Peak
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - start
        sequence:
          - service: select.select_option
            data:
              option: Time-Based Control
            target:
              entity_id: select.home_operation_mode
          - service: select.select_option
            data:
              option: "Yes"
            target:
              entity_id: select.home_grid_charging
          - service: number.set_value
            data_template:
              value: >-
                {{ states('input_number.powerwall_charge_threshold') | int - 10
                }}
            target:
              entity_id: number.home_backup_reserve
      - conditions:
          - condition: trigger
            id:
              - stop
        sequence:
          - service: select.select_option
            data:
              option: "No"
            target:
              entity_id: select.home_grid_charging
  - if:
      - condition: not
        conditions:
          - condition: state
            entity_id: select.electric_import
            state: Off-Peak
    then:
      - service: select.select_option
        data:
          option: Self-Powered
        target:
          entity_id: select.home_operation_mode
      - if:
          - condition: state
            entity_id: binary_sensor.octopus_free_power_24h
            state: "on"
        then:
          - service: number.set_value
            data:
              value: "1"
            target:
              entity_id: number.home_backup_reserve
            enabled: true
        else:
          - service: number.set_value
            data:
              value: "10"
            target:
              entity_id: number.home_backup_reserve
            enabled: true
mode: single
```

Export Automation
```YAML
alias: Powerwall Export
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.discharge_house_battery
    id: start
    to: "on"
    from: null
  - platform: state
    entity_id:
      - select.electric_export
    from: Peak
    id: stop
  - platform: state
    entity_id:
      - binary_sensor.discharge_house_battery
    id: stop
    to: "off"
    from: null
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - start
        sequence:
          - service: select.select_option
            data:
              option: Time-Based Control
            target:
              entity_id: select.home_operation_mode
          - service: select.select_option
            data:
              option: "Yes"
            target:
              entity_id: select.home_grid_charging
          - service: select.select_option
            data:
              option: Everything
            target:
              entity_id: select.home_energy_exports
      - conditions:
          - condition: trigger
            id:
              - stop
        sequence:
          - service: select.select_option
            data:
              option: Solar
            target:
              entity_id: select.home_energy_exports
  - if:
      - condition: not
        conditions:
          - condition: state
            entity_id: select.electric_export
            state: Peak
    then:
      - service: select.select_option
        data:
          option: "No"
        target:
          entity_id: select.home_grid_charging
      - service: select.select_option
        data:
          option: Self-Powered
        target:
          entity_id: select.home_operation_mode
mode: single
```
