### DISCUSSION TITLE
Email address issue with tesla_custom.api

### DISCUSSION THREAD

**Discussion by d3marcus** [alandtse/tesla#182] [General]
I have trouble when using the tesla_custom.api service.

If I omit email address i get an error message that email address is missing. If I include email address I get the error message: "_No Tesla controllers found for email <my email address>_"

Everything else is working with the integration, like Lovelace cards etc. I have the latest version, restarted HA etc.

My script:

```
alias: Set charge limit to 90
sequence:
  - service: tesla_custom.api
    data:
      command: CHANGE_CHARGE_LIMIT
      email: <my email address>
      parameters:
        path_vars:
          vehicle_id: '{{ state_attr(''binary_sensor.my_car_online_sensor'', ''id'') }}'
        percent: '90'
        wake_if_asleep: true
mode: single
```

Any help appreciated.

**Comment by alandtse** [comment]
https://github.com/alandtse/tesla/wiki/Modify-Charge-Limit

**Reply by d3marcus** [reply]
Yeah the issue is with the email address using tesla_custom.api, not the particular CHANGE_CHARGE_LIMIT call. I get the same error message when calling other Tesla commands like STATUS.

**Reply by alandtse** [reply]
Why are you adding an email parameter?

**Reply by d3marcus** [reply]
From the log file:

**When I use email address in call:**

_File "/config/custom_components/tesla_custom/services.py", line 102, in api
    raise ValueError(f"No Tesla controllers found for email {email}")_

**When I omit email address:**

  _File "/config/custom_components/tesla_custom/services.py", line 92, in api
    raise ValueError("Email address missing")_

**Reply by d3marcus** [reply]
I get the error message _Email address missing_ when not adding email address.

**Reply by alandtse** [reply]
Delete the email key unless you have multiple logins.

**Reply by d3marcus** [reply]
With this code I get the error message "Email address missing":

```
alias: Set charge limit to 90
sequence:
  - service: tesla_custom.api
    data:
      command: CHANGE_CHARGE_LIMIT
      parameters:
        path_vars:
          vehicle_id: '{{ state_attr(''binary_sensor.my_car_online_sensor'', ''id'') }}'
        percent: '90'
        wake_if_asleep: true
mode: single
```
