### DISCUSSION TITLE
Camp mode in the API?

### DISCUSSION THREAD

**Discussion by yurgh** [alandtse/tesla#224] [General]
I've been searching for ways to be able to set the climate control to Camp Mode, since it's now possible in the Tesla app. But; I can't seem to find anything. Is it doable? Edit; it's in the API: https://tesla-api.timdorr.com/vehicle/commands/climate#post-api-1-vehicles-id-command-set_climate_keeper_mode

In winter my Model 3 will expend tremendous amounts of battery and grid power to heat the batteries when defrosting, unlike camp mode which only heat the interior. At least 5kW/h down the drain every morning...

**Comment by yurgh** [comment]
As it turns out; this is possible if setting mode by number instead of name:

```
service: tesla_custom.api
data_template:
  email: my@email.info
  command: SET_CLIMATE_KEEPER_MODE
  parameters:
    path_vars:
      vehicle_id: "{{state_attr('binary_sensor.tesla_online_sensor', 'id')}}"
    wake_if_asleep: true
    climate_keeper_mode: 3
```

0 = off
1 = on
2 = dog mode
3 = camp mode
