### DISCUSSION TITLE
How to change charging amps in increments

### DISCUSSION THREAD

**Discussion by austin202220** [alandtse/tesla#464] [Q&A]
I have the service call working where I can set a specific number, 8 amps for example. How can I change it incrementally instead of using a specific number?

This works:
service: tesla_custom.api
data:
  command: CHARGING_AMPS
  parameters:
    path_vars:
      vehicle_id: "3744492401xxxxxx"
    charging_amps: "8"

This is the code I am trying but cant get to work. I get 'unknown error'.

service: tesla_custom.api
data:
  command: CHARGING_AMPS
  parameters:
    path_vars:
      vehicle_id: "3744492401xxxxxx"
    charging_amps: {{ state_attr("sensor.zoomie_charging_rate", "charge_current_request")+1 }}

original source was here:
https://www.reddit.com/r/homeassistant/comments/vngjao/automation_to_vary_ev_charge_rate_based_on_excess/?utm_name=iossmf

**Comment by InTheDaylight14** [comment]
In v3 there is an entity dedicated to the charger amps. Search for "number.<car_name>_charging_amps if you have that version of the integration added. Check out it's history and see if it would work. 

The new service call to increment should look something like this:
```
service: number.set_value
data:
  value: {{states('number.<car_name>_charging_amps')}} + 1
target:
  entity_id: number.<car_name>_charging_amps
```
