### DISCUSSION TITLE
Variable charging speed

### DISCUSSION THREAD

**Discussion by maart84** [alandtse/tesla#85] [Show and tell]
First of all: thank you for this plugin! 

I just received the 2021.36 firmware in my car so now I can change the charging speed from the app Tesla app (and the api). I thought others might like it as well. If you call the service like this from the developer tool in Home Assistant you can change the charging speed:

```
service: tesla_custom.api
data:
  command: CHARGING_AMPS
  parameters:
    path_vars:
      vehicle_id: 'xxxxxxx'
    charging_amps: '5'
```

Now the next challenge is to make a nice script or blueprint to change this speed based on solar over-production so we can fill the car with only solar power.
