### ISSUE TITLE
Did not find custom-components/tesla (0)

### ISSUE THREAD

**Issue by fastender** [alandtse/tesla#100]
Newest Version of the custom_component

```yaml
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.hacs
Source: custom_components/hacs/hacsbase/data.py:177 
Integration: HACS (documentation, issues) 
First occurred: 19:07:00 (1 occurrences) 
Last logged: 19:07:00

Did not find custom-components/tesla (0)

```

I am not able to delete the integration. I get this error message.
