### ISSUE TITLE
It would be great to have the ability to turn Storm Watch on and off.

### ISSUE THREAD

**Issue by Obioban** [alandtse/tesla#1004]
For those of use on Time of Use power, Storm Watch is very much a double edged storm. I generally like to have storm watch on, but I don't want it to be charging the house batteries in the 4 hours of SUPER expensive power on week days. 

If the Tesla HACs integration could turn Storm Watch on and off, I could set up HA to turn off storm watch at 2pm on weekdays and turn on storm watch at 6pm on weekdays-- only slightly decreasing the effectiveness of Storm Watch, but making it so I don't get hit by stupidly expensive bills randomly. 

Any possibility of this happening?

**Comment by dandelionclock** [comment]
Have you tried calling the API in developer tools -> services? Try

```
service: tesla_custom.api
data:
  email: <email@domain.com>
  command: STORM_MODE_SETTINGS
  parameters:
    path_vars:
      site_id: <your_energy_site_id>
    enabled: true
```
