### ISSUE TITLE
Climate entity "does not support action climate.turn_on"

### ISSUE THREAD

**Issue by rubin110** [alandtse/tesla#1089]
### Is there an existing issue for this?

- [x] I have searched both the existing open issues & recently closed issues and did not find a duplicate of this issue.

### I have read about the Fleet API and understand I may need to use it

- [x] I understand issues relating to read only commands will be auto closed if not using the Fleet API.

### Version of the Tesla component

3.24.3

### Version of the Tesla car software

2024.44.25.2 288ce84bb43e

### Model

Model 3 LR/AWD 2021

### Current Behavior

When running the `climate.turn_on`, `climate.turn_off`, or `climate.toggle` actions on the Tesla climate entity...

```yaml
action: climate.turn_on
target:
  entity_id: climate.setareh_hvac_climate_system
data: {}
```

An error is thrown...

```
Entity climate.setareh_hvac_climate_system does not support action climate.turn_on
```

And the action doesn't execute.

### Expected Behavior

When running the `climate.turn_on`, `climate.turn_off`, or `climate.toggle` actions on the Tesla climate entity, the action executes successfully, turning on the HVAC system in the car.

### Debug logs

```true
2025-01-22 17:03:00.630 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Error for call_service at pos 1: Entity climate.setareh_hvac_climate_system does not support action climate.turn_on
2025-01-22 17:03:00.630 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139702177610720] Entity climate.setareh_hvac_climate_system does not support action climate.turn_on
```

### Anything else?

I've tested this both with and without MQTT. I can tell you this was working at least a month ago. `climate.set_hvac_mode` does work....

```yaml
action: climate.set_hvac_mode
data:
  hvac_mode: heat_cool
target:
  entity_id: climate.setareh_hvac_climate_system
```

I don't think I've ever seen a climate entity not respond to the on/off/toggle actions.

I do see [that's something that can be set](https://developers.home-assistant.io/docs/core/entity/climate/#supported-features) for climate entities. When I take a look at the entity attributes...

```
hvac_modes:
  - heat_cool
  - "off"
min_temp: 59
max_temp: 82
fan_modes:
  - "off"
  - bioweapon
preset_modes:
  - normal
  - defrost
  - keep
  - dog
  - camp
current_temperature: 72
temperature: 72
fan_mode: "off"
preset_mode: normal
attribution: Data provided by Tesla
friendly_name: Setareh Hvac (climate) system
supported_features: 25
```

I'm guessing tweaking `supported_features` would open up the ability to turn the entity on and off, but I'm not sure where to start with modifying that.

Thanks!

**Comment by bbrendon** [comment]
May be related: https://github.com/alandtse/tesla/issues/1063

I was using both defrost and turn_on. Both are dead. I switched to hvac_mode: heat_cool

**Comment by DHT-Xavier** [comment]
Still not working until today ?
```yaml
action: climate.set_hvac_mode
target:
  entity_id: climate.xxxxxxxxx_hvac_climate_system
data:
  hvac_mode: heat_cool
```
```
Failed to perform the action climate.set_hvac_mode. Unknown error
```
