### ISSUE TITLE
Force data update if sensors unknown?

### ISSUE THREAD

**Issue by torsteinelv** [alandtse/tesla#1090]
This can be solved with an automation also. But guess many users has this problem if sensors have become unknown the integration can run an update to get the data updated again?

**Comment by skipishere** [comment]
This is part of my Home Assistant has restarted automation, where sometimes the car info becomes Unknown (doesn't always happen hence the `if`)
![Image](https://github.com/user-attachments/assets/839b25f2-7cff-4f22-a18f-7c39994b6d53)
```

if:
  - condition: state
    entity_id: sensor.tesla_m3_battery
    state: unknown
then:
  - device_id: 7256a937bc19c0302efd1542955a7c8c
    domain: button
    entity_id: cf03f1c11aa413a9e7cd58bd5ebfc588
    type: press
```
Slightly annoying Home Assistant turns them into device and entity ids that are GUIDs
