### ISSUE TITLE
feat: add ability to force refresh a car

### ISSUE THREAD

**Issue by scottda4270** [alandtse/tesla#120]
Hi all
I am using the latest 1.4 integration, great work by the way so thank you!

I have a few node red calls from HASS OS to the Tesla, all working fine. However i was wondering if anyone could offer up a solution on how i refresh the data of the Tesla integration in HASS OS from nodered. I need to be able to do things based on the 'current' state of the car, not the last known poll state of the car. So ideally a way of injecting a 'refresh' on demand from node red...is that possible?
thank you

**Comment by Olen** [comment]
I think a way to do this is to issue a service call. I don't have Node Red, so I cant help you with that part, but I have some yaml-scripts that isses the command
```
  - service: tesla_custom.api
    data:
      command: WAKE_UP
      parameters:
        path_vars:
          vehicle_id: "{{ state_attr('binary_sensor.my_car_online_sensor', 'id') }}"
        wake_if_asleep: true
```
This should wake the car up.

Unfortunately, there is no way to force the polling right now.  But one idea I had was if there was a possibility to set "scan_interval" using a service call.  There is code for updating the scan_interval in the function `update_listener`in `__init__.py`, so it should be doable to create a service call to set this to a lower value, and thereby cause the data to be refreshed.

Having a service call to do this would also allow you to do other tricks, like lowering the scan_interval when you are connected to a charger, while increasing it when you are parked in certain locations where you know you want the car to sleep.
