### ISSUE TITLE
Losing authorization

### ISSUE THREAD

**Issue by hesspoint** [alandtse/tesla#130]
I installed the integration and it works great. However after a few weeks it loses the authorization it seems. I guess the token expires after a while that makes sense. However I did not find a way to enter a new token. I did reinstall the integration but that is quite inconvenient. Is there a way to update the token from the HA interface?

**Comment by mcowger** [comment]
When you pasted your token, did you paste a refresh token?

**Comment by automaton82** [comment]
Same issue here. Won't refresh anymore, I assume I lost auth. No way to update token for some reason? Why can't we in the UI update the token.

**Comment by goobags** [comment]
Some thing happened to me, can’t remember which token I used but did a restart of HA this morning and the integration failed to load. Either we all used a refresh token which gets refreshed all at the same time or there was something happening on the Tesla side.

**Comment by mcowger** [comment]
I regenerated a new refresh token and still can't get it to auth.

**Comment by alandtse** [comment]
Please provide logs from tesla_custom and teslajsonpy. The component should create a prompt if it detects a relogin is necessary. Regardless you can remove and readd.

**Comment by automaton82** [comment]
I never got that warning in my log. However HACS requested an update and after restarting the integration did prompt for a new refresh token, finally. This solved the errors.

**Comment by ervwalter** [comment]
Mine also required reauthentication today (the UI for reauthentication worked fine).  

It seems like a coincidence that it happened to several people today?  Could there have been a hiccup in Tesla's servers that the integration interpreted as a permanently failed authentication or something?

**Comment by goobags** [comment]
Re-authentication through the UI fixed the integration for me

**Comment by mcowger** [comment]
I added the following to my configuration.yaml:

```

logger:
  default: info
  logs:
    homeassistant.core: info
    homeassistant.components.command_line.switch: warning
    googleapiclient.discovery: warning
    custom_components.openei: warning
    custom_components.tesla_custom: debug
    custom_components.teslajsonpy: debug
    tesla_custom: debug
    teslajsonpy: debug
```

and I'm not seeing deeper logs.  When I attempt the config flow:

This error originated from a custom integration.

```
Logger: custom_components.tesla_custom.config_flow
Source: custom_components/tesla_custom/config_flow.py:172
Integration: tesla_custom (documentation, issues)
First occurred: 10:37:01 PM (1 occurrences)
Last logged: 10:37:01 PM

Authentication error: Need oauth credentials
```
