### ISSUE TITLE
Once Status Polling is Disabled and the switch cannot be enabled

### ISSUE THREAD

**Issue by bakerbug** [alandtse/tesla#142]
## Version of the custom_component
1.5.0

## Configuration

<details>

```yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
homeassistant:
  customize: !include customize.yaml
frontend:
  themes: !include_dir_merge_named themes

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  cors_allowed_origins:
    - http://10.99.10.10:8123

logger:
  default: warn
  logs:
    custom_components.tesla_custom: debug


# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
group: !include groups.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

recorder:
  purge_keep_days: 7
  db_url: 'sqlite:///:memory:'
  exclude:
    entities:
      - sun.sun

# Cloud
cloud:
  alexa:
    filter:
      include_entities:
        - cover.left_bay
        - cover.right_bay
        - fan.bedroom_fan
        - fan.living_room_ceiling_fan
        - group.bedroom_lights
        - group.bridge_lights
        - group.kitchen_lights
        - group.bright_kitchen
        - group.livingroom_lights
        - input_boolean.clean_house
        - input_boolean.enable_fan_control
        - input_boolean.fireplace_temperature
        - input_boolean.respond_pollen_monitor
        - input_boolean.satellite_report
        - input_boolean.secure_house
        - input_boolean.status_report
        - input_boolean.tesla_hvac_enable
        - input_boolean.weather_alert_details
        - switch.humidifier
        - switch.power_strip_dishwasher_socket_2 # Coffee Maker
        - switch.bedroom_power_strip_socket_2 # Bill's CPAP
        - switch.guest_exhaust_fan
        - switch.meco_polling_switch
        - switch.wemo_delta # printer
      exclude_domains:
        - alert
        - automation
        - binary_sensor
        - camera
        - climate
        - fan
        - group
        - input_boolean
        - input_number
        - lock
        - media_player
        - scene
        - script
        - sensor
        - switch
        - timer
      exclude_entities:
        - climate.downstairs
        - climate.upstairs
        - group.appliances
        - group.bed
        - group.garage_doors
        - light.dishwasher_counter_light
        - light.stove_counter_light
        - light.ceiling_dishwasher_left
        - light.ceiling_dishwasher_right
        - light.ceiling_stove_left
        - light.ceiling_stove_right


history:
    use_include_order: True
    include:
        entities:
            - weather.khsv
            - sun.sun
            - binary_sensor.workday
            - binary_sensor.bayberry_away
            - sensor.bill_location
            - sensor.cricket_location
            - device_tracker.meco_location_tracker
            - lock.front_door
            - lock.back_door
            - cover.left_bay
            - cover.right_bay
            - binary_sensor.front_door_cam_motion
            - binary_sensor.driveway_cam_motion
            - binary_sensor.backyard_cam_motion
            - sensor.master_bedroom_nest_protect_smoke_status
            - sensor.kids_room_nest_protect_smoke_status
            - sensor.master_bedroom_nest_protect_co_status
            - sensor.kids_room_nest_protect_co_status
            - sensor.upstairs_thermostat_temperature
            - sensor.downstairs_thermostat_temperature
            - sensor.weather_temperature
            - sensor.upstairs_thermostat_humidity
            - sensor.downstairs_thermostat_humidity
            - sensor.weather_humidity
            - sensor.upstairs_thermostat_hvac_state
            - sensor.downstairs_thermostat_hvac_state
            - sensor.fan_speed
            - sensor.bedroom_fan_speed
            - switch.wemo_alpha
            - switch.humidifier
            - switch.guest_exhaust_fan
            - switch.power_strip_dishwasher_socket_2
            - vacuum.puck
            - sensor.sleepnumber_bill_bill_sleepnumber
            - sensor.sleepnumber_bill_cricket_sleepnumber
            - binary_sensor.sleepnumber_bill_bill_is_in_bed
            - binary_sensor.sleepnumber_bill_cricket_is_in_bed
            - media_player.living_room
            - media_player.playstation_4
            - media_player.bedroom_tv
            - light.driveway_light
            - light.front_door_light
            - light.patio_light
            - light.bedroom_lamp
            - light.bill_s_lamp
            - light.cricket_s_lamp
            - light.bedroom_dimmer
            - light.bottle_lamp
            - light.entry_lamp
            - light.sofa_lamp
            - light.corner_lamp
            - light.sky_lights
            - light.shelf_lights
            - light.island_light
            - switch.upper_bridge
            - switch.lower_bridge
            - light.sink_light
            - light.counter_lights
            - light.ceiling_lights
            - light.dining_room_light
            - light.computer_room_light
            - light.guest_bathroom
            - light.garage_light
            - light.kyle_s_light
            - light.lava_lamp
            - switch.wemo_delta
    exclude:
        domains:
            - automation
        entities:
            - sensor.bayberry_eta
            - sensor.weather_symbol
            - group.bed
            - group.garage


light:
  # Computer Room
  - platform: switch
    name: Computer Room Light
    entity_id: switch.computer_room
  # Kitchen
  - platform: switch
    name: Stove Counter Light
    entity_id: switch.power_strip_stove_socket_4
  - platform: switch
    name: Dishwasher Counter Light
    entity_id: switch.power_strip_dishwasher_socket_1

  - platform: group
    name: Bridge Lights
    entities:
      - light.upper_bridge
      - light.lower_bridge

  - platform: group
    name: Counter Lights
    entities:
      - light.stove_counter_light
      - light.dishwasher_counter_light

  - platform: switch
    name: Ceiling Stove Left
    entity_id: switch.power_strip_stove_socket_2
  - platform: switch
    name: Ceiling Stove Right
    entity_id: switch.power_strip_stove_socket_3
  - platform: switch
    name: Ceiling Dishwasher Left
    entity_id: switch.power_strip_dishwasher_socket_3
  - platform: switch
    name: Ceiling Dishwasher Right
    entity_id: switch.power_strip_dishwasher_socket_4

  - platform: group
    name: Ceiling Lights
    entities:
      - light.ceiling_stove_left
      - light.ceiling_stove_right
      - light.ceiling_dishwasher_left
      - light.ceiling_dishwasher_right

  - platform: switch
    name: Sink Light
    entity_id: switch.sink_light

  - platform: switch
    name: Island Light
    entity_id: switch.island_light

#  # Dining Room
  - platform: switch
    name: Dining Room Light
    entity_id: switch.dining_room_light

  # Master Bedroom
  - platform: switch
    name: Bill's Lamp
    entity_id: switch.bedroom_power_strip_socket_1

  - platform: switch
    name: Cricket's Lamp
    entity_id: switch.bedroom_power_strip_socket_4

  - platform: switch
    name: Bedroom Lamp
    entity_id: switch.bedroom_lamp

  # Living Room
  - platform: switch
    name: Sky Lights
    entity_id: switch.living_room_power_bar_socket_3

  - platform: switch
    name: Shelf Lights
    entity_id: switch.living_room_power_bar_socket_4

  - platform: switch
    name: Corner Lamp
    entity_id: switch.living_room_power_bar_socket_2

  - platform: switch
    name: Sofa Lamp
    entity_id: switch.sofa_lamp

  - platform: switch
    name: Entry Lamp
    entity_id: switch.entry_lamp

  - platform: switch
    name: Bottle Lamp
    entity_id: switch.wemo_echo

  # Kyle's Room
  - platform: switch
    name: Kyle's Light
    entity_id: switch.wemo_bravo

  - platform: switch
    name: Lava Lamp
    entity_id: switch.wemo_charlie

  # Guest Bathroom
  - platform: switch
    name: Guest Bathroom
    entity_id: switch.guest_bathroom

  # Outdoor Lights
  - platform: switch
    name: Driveway Light
    entity_id: switch.driveway_light

  - platform: switch
    name: Front Door Light
    entity_id: switch.front_door_light

  - platform: switch
    name: Patio Light
    entity_id: switch.patio_light



media_player:
  - platform: yamaha

# Nest
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret


# Sensors
sensor:
  - platform: statistics
    entity_id: sensor.meco_mileage_sensor
    name: Mileage Stats

  - platform: time_date
    display_options:
      - 'time'
  - platform: template
    sensors:
      air_quality_downstairs:
        device_class: "aqi"
        friendly_name: "Air Quality Downstairs"
        value_template: "{{ states.fan.winix_living_room.attributes.air_qvalue }}"
      air_quality_upstairs:
        device_class: "aqi"
        friendly_name: "Air Quality Upstairs"
        value_template: "{{ states.fan.winix_office.attributes.air_qvalue }}"
      fan_speed:
        friendly_name: "Ceiling Fan Speed"
        value_template: "{{ states.fan.living_room_ceiling_fan.attributes.speed }}"
      bedroom_fan_speed:
        friendly_name: "Bedroom Fan Speed"
        value_template: "{{ states.fan.bedroom_fan.attributes.speed }}"
      sun_elevation:
        friendly_name: "Sun Elevation"
        value_template: "{{ states.sun.sun.attributes.elevation }}"
      bill_location:
        friendly_name: "Bill's Location"
        value_template: "{{ states.device_tracker.life360_bill_baker.attributes.place }}"
      cricket_location:
        friendly_name: "Cricket's Location"
        value_template: "{{ states.device_tracker.life360_cricket.attributes.place }}"
      last_alexa:
        friendly_name: "Active Alexa"
        entity_id:
          - media_player.computer_room
          - media_player.kitchen
          - media_player.kyle_s_room
          - media_player.master_bedroom
          - media_player.guest_bathroom
          - media_player.echo_auto_camry
          - media_player.garage
        value_template: >
          {{ states.media_player | selectattr('attributes.last_called','eq',True) | map(attribute='entity_id') | first }}
      washing_machine_power:
        friendly_name: "Washing Machine Power"
        value_template: "{{ states.switch.washing_machine.attributes.current_power_w }}"
        unit_of_measurement: "Watts"
      weather_humidity:
        friendly_name: "Outdoor Humidity"
        unit_of_measurement: "%"
        value_template: "{{ states.weather.khsv.attributes.humidity }}"
      weather_temperature:
        friendly_name: "Outdoor Temperature"
        unit_of_measurement: "\u00B0F"
        value_template: "{{ states.weather.khsv.attributes.temperature }}"

  - platform: version
    name: Installed HA Version
    source: local

  - platform: version
    name: Available HA Version
    source: pypi

  - platform: weatheralerts
    state: AL
    zone: 6
    county: 89

# Slack
notify:
  - name: Slack_Assistant
    platform: slack
    api_key: !secret slack_api_key
    default_channel: '#home'

python_script:

# Sleep Number Bed
sleepiq:
  username: !secret sleepnumber_user
  password: !secret sleepnumber_password

# Custom Sensors
binary_sensor:
    - platform: workday
      name: Workday
      country: US

# Custom Switches
switch:
  - platform: template
    switches:
      humidifier:
        friendly_name: "Humidifier"
        value_template: "{{ is_state('switch.living_room_power_bar_socket_1', 'on') }}"
        turn_on:
          - service: switch.turn_on
            data:
              entity_id: switch.living_room_power_bar_socket_1
          - service: automation.turn_off
            data:
              entity_id: automation.restart_humidifier
        turn_off:
          - service: automation.turn_on
            data:
              entity_id: automation.restart_humidifier
          - service: switch.turn_off
            data:
              entity_id: switch.living_room_power_bar_socket_1

# Timers
timer:
  motion_debounce:
    duration: '00:01:00'
  wakup_light:
    duration: '00:02:00'

input_boolean:
  announce_all:
    name: Alexa Anouncements
    icon: mdi:amazon-alexa
  active_sleep_monitor:
    name: Sleep Monitor
    icon: mdi:language-python
  battery_monitor:
    name: Battery Monitor
    initial: off
    icon: mdi:battery
  bus_notify:
    name: Bus Notify
    initial: off
    icon: mdi:bus-school
  clean_house:
    name: Clean House
    icon: mdi:robot-vacuum
  environment_report:
    name: Environment Report
    icon: mdi:home-thermometer-outline
  enable_fan_control:
    name: Fan Control
    icon: mdi:home-assistant
  fireplace_temperature:
    name: Fireplace Temperature
    initial: off
    icon: mdi:fireplace
  location_monitor:
    name: Location Monitor
    icon: mdi:map-marker
  motion_lights:
    name: Motion Lights
    icon: mdi:motion-sensor
  satellite_report:
    name: Satellite Report
    icon: mdi:space-station
  secure_house:
    name: Secure The House
    icon: mdi:shield-home-outline
  tesla_hvac_enable:
    name: Tesla HVAC Enable
    icon: mdi:air-conditioner
  tesla_record_range:
    name: Tesla Record Range
    icon: mdi:car-electric
  wakeup_light:
    name: Wakeup Light
    icon: mdi:alarm
  wakeup_light_weekend:
    name: Weekend Wakeup Light
    icon: mdi:alarm
  weather_alert_details:
    name: Weather Alert Details
    icon: mdi:weather-lightning

  # DEBUG
  debug_alexa_speak:
    icon: mdi:bug-check-outline
  debug_bus_notify:
    icon: mdi:bug-check-outline
  debug_clean_house:
    icon: mdi:bug-check-outline
  debug_fan_control:
    icon: mdi:bug-check-outline
  debug_fireplace_temp:
    icon: mdi:bug-check-outline
  debug_garage_monitor:
    icon: mdi:bug-check-outline
  debug_laundry:
    icon: mdi:bug-check-outline
  debug_location_monitor:
    icon: mdi:bug-check-outline
  debug_pollen_monitor:
    icon: mdi:bug-check-outline
  debug_reminders:
    icon: mdi:bug-check-outline
  debug_satellite_monitor:
    icon: mdi:bug-check-outline
  debug_sleep_monitor:
    icon: mdi:bug-check-outline
  debug_version_monitor:
    icon: mdi:bug-check-outline
  debug_wakeup_light:
    icon: mdi:bug-check-outline
  debug_weather_alert:
    icon: mdi:bug-check-outline

  # NOTIFY
  notify_away_monitor:
    icon: mdi:message-text

  notify_fan_control:
    icon: mdi:message-text

  announce_location_change:
    name: Announce Locations
    icon: mdi:amazon-alexa
  announce_lock_change:
    name: Announce Lock Change
    icon: mdi:key-variant
  announce_oven_monitor:
    name: Announce Oven Temperature
    icon: mdi:amazon-alexa
  announce_weather_alert:
    name: Announce Weather Alert
    icon: mdi:weather-lightning

  notify_location_monitor:
    icon: mdi:message-text
  respond_pollen_monitor:
    name: Pollen Monitor Response
    icon: mdi:tree-outline

  notify_pollen_monitor:
    icon: mdi:message-text

  status_report:
    icon: mdi:lock-question

input_number:
  fireplace_max_indoor_temp:
    name: Max Indoor Temperature
    min: 65
    max: 70
    icon: mdi:fireplace
  fireplace_max_outdoor_temp:
    name: Max Outdoor Temperature
    min: 45
    max: 60
    icon: mdi:fireplace
  fireplace_shutdown_temp:
    name: Shutdown Temperature
    min: 69
    max: 75
    icon: mdi:fireplace
  bedroom_fan_low_temp:
    name: Bedroom Fan Low Temperature
    min: 65
    max: 75
    icon: mdi:fan

input_datetime:
  wakeup_time:
    name: Wakeup Time
    has_date: false
    has_time: true
    icon: mdi:alarm

winix:
  username: !secret winix_username
  password: !secret winix_password

```

</details>

## Describe the bug

I have some automations configured to enable and disable Tesla polling in order to allow my car to enter deep sleep.  Once I disable polling, I can not re-enable it without completely reloading the Tesla integration.  Note in the debug logs below, there is a single message of `Disable polling` followed by two instances of `Enable polling`.  I manually disabled polling, then re-enabled it.  Polling then disabled itself, then I manually re-enabled it.  The failure case did not leave a debug entry for `Disable polling`.

## Debug log

```text

2022-02-08 15:30:25 DEBUG (MainThread) [custom_components.tesla_custom] Finished fetching tesla_custom data in 0.993 seconds (success: True)
2022-02-08 15:30:34 DEBUG (MainThread) [custom_components.tesla_custom.switch] Disable polling: Meco polling switch 1492934466762828
2022-02-08 15:30:57 DEBUG (MainThread) [custom_components.tesla_custom.switch] Enable polling: Meco polling switch 1492934466762828
2022-02-08 15:31:25 DEBUG (MainThread) [custom_components.tesla_custom] Running controller.update()
2022-02-08 15:31:25 DEBUG (MainThread) [custom_components.tesla_custom] Finished fetching tesla_custom data in 0.459 seconds (success: True)
2022-02-08 15:32:13 DEBUG (MainThread) [custom_components.tesla_custom.switch] Enable polling: Meco polling switch 1492934466762828
2022-02-08 15:32:25 DEBUG (MainThread) [custom_components.tesla_custom] Running controller.update()
2022-02-08 15:32:25 DEBUG (MainThread) [custom_components.tesla_custom] Finished fetching tesla_custom data in 0.461 seconds (success: True)

```
