### ISSUE TITLE
Tire Pressure Sensors

### ISSUE THREAD

**Issue by giggo** [alandtse/tesla#160]
Apparently the tire pressure is now available via the Tesla API ( [https://www.notateslaapp.com/de/software-updates/version/2022.4.5/versionshinweise](https://www.notateslaapp.com/de/software-updates/version/2022.4.5/versionshinweise) ). Are there plans to add them as sensors to HA?

**Comment by alandtse** [comment]
People are welcome to submit PRs to add features.

**Comment by k-korn** [comment]
TPMS data is available in the following attributes of "vehicle_state" :
tpms_pressure_fl
tpms_pressure_fr
tpms_pressure_rl
tpms_pressure_rr

However, quick look on https://github.com/alandtse/tesla/blob/dev/custom_components/tesla_custom/sensor.py suggests that [teslajsonpy ](https://github.com/zabuldon/teslajsonpy) should also be modified to add this data.

**Comment by k-korn** [comment]
With version 2.0 it is now possible to use now exposed vehicle_data to display TPMS sensors in HASS.
- on Config/Devices page, enable "sensor.model_3_vehicle_state_data_sensor" in Tesla integration, which is disabled by default
- Create 4 Template sensors as follows for FL, FR, RL, RR sensors:
```
 template:
    sensors:
     - name: "Tesla TPMS FL"
       state: >
        {% set tpms = state_attr("sensor.model_3_vehicle_state_data_sensor", "tpms_pressure_fl") %}
        {{ tpms|round(2) if tpms != None else states('sensor.tesla_tpms_fl') }}
       unit_of_measurement: "PSI"
```
Extra steps with intermediate variable were added to remove "Unavailable" TPMS sensor state values and keep actual values visible.
Then we can use something like a Grid Lovelace card to display tire pressures: https://i.imgur.com/4gpfwJj.png
