### ISSUE TITLE
Tesla doesn't wake up when set HVAC to heat_cool

### ISSUE THREAD

**Issue by dawiinci** [alandtse/tesla#162]
If I set this (or probably any) command and the car is at sleep, it won't activate. It will however, wake the car. If I send the command again it activates HVAC.

It should first wake the car and then send the command.

Can I wake the car without sending commands? Because the underlying python script allows for that.

**Comment by alandtse** [comment]
Please provide logs for teslajsonpy showing the attempt to wake up.

**Comment by jherby2k** [comment]
this seems to be an API quirk - i wrote a script to wake up the car if its asleep. just call it before setting HVAC.

```yaml
alias: Wake up car
sequence:
  - condition: state
    entity_id: binary_sensor.sonic_online_sensor
    state: 'off'
  - service: tesla_custom.api
    data:
      command: WAKE_UP
      parameters:
        path_vars:
          vehicle_id: '{{ state_attr(''binary_sensor.<name>_online_sensor'', ''id'') }}'
  - wait_template: '{{ is_state(''binary_sensor.<name>_online_sensor'', ''on'') }}'
    timeout: '2:00'
mode: single
icon: mdi:car-connected
```
