### ISSUE TITLE
Windows vent switch/window control

### ISSUE THREAD

**Issue by ilvar** [alandtse/tesla#234]
Since Cabin Overheat Protection requires Tilt/Intrusion Alarm to be **off** and Sentry Mode requires Intrusion Alarm to be **on**, we can't have both Overheat Protection and Sentry Mode. 
 
I think it would be nice to have a Switch or Window exposed to activate Vent when the car is at Home, and it's too hot outside.

I've tried to use HVAC controls for that, but it's less reliable. Also, turning HVAC off when the cabin cools down means that it will be off during the next ride.

**Comment by InTheDaylight14** [comment]
I made a custom cover a while back using the custom tesla API call service. It's not working right now but was nice for a while. 

```
cover:
  - platform: template
    covers:
      tesla_windows:
        device_class: window
        friendly_name: "Tesla Windows"
        open_cover:
          - service: tesla_custom.api
            data:
              command: WINDOW_CONTROL
              parameters:
                path_vars:
                  vehicle_id: 'my_id'
                command: vent
                lat: 0
                long: 0
                wake_if_asleep: true
        close_cover:
          - service: tesla_custom.api
            data:
              command: WINDOW_CONTROL
              parameters:
                path_vars:
                  vehicle_id: 'my_id'
                command: close
                lat: 0
                long: 0
                wake_if_asleep: true
```
