### ISSUE TITLE
No longer shows in Miles only km

### ISSUE THREAD

**Issue by ad2022uk** [alandtse/tesla#284]
New version 3.x shows everything in Kms and not miles. Why has this changed?

**Describe the solution you'd like**
All metrics in Kms rather than miles.

**Describe alternatives you've considered**
Reinstate miles as option. 

**Additional context**
Was present in 2.x correctly.

**Comment by alandtse** [comment]
This should be controlled by your HA UI settings now. @shred86 please confirm.

**Comment by ad2022uk** [comment]
Tried changing HA to imperial units and it still shows KM

**Comment by the-yews-consulting** [comment]
added imperial to configuration.yaml
homeassistant:
  unit_system: imperial
  
  and working ok now

**Comment by ad2022uk** [comment]
Yes I will try this

However in the UK we used mixed units

Miles but celcius for temperature.

The previous method worked well 
Not sure why it was changed.

**Comment by the-yews-consulting** [comment]
@ad2022uk 
To get around this just, forget the unit_system update to configuration.yaml and add these custom settings to _customize.yaml_ (remember to add  customize.yaml to configuration.yaml)
```
sensor.tesla_odometer:
  unit_of_measurement: "mi"
sensor.tesla_range:
  unit_of_measurement: "mi"   
sensor.tesla_charging_rate:
  unit_of_measurement: "mph" 
```
