### ISSUE TITLE
Sunroof Control Open/Close/Vent is missing

### ISSUE THREAD

**Issue by mobile26** [alandtse/tesla#287]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by shred86** [comment]
This should be easy to add. There's a key "sun_roof_installed" in "vehicle_config" we could just check before adding this. I can try to get this added when I have a bit more time (maybe tomorrow).

**Comment by ve6rah** [comment]
Just a quick bump on this and to see the status? I thought this used to be in the integration at some point in the past?
Thanks!

**Comment by KE55ARD** [comment]
Bump, as I just noticed this isn't in there too.

Would like to add to my "auto close boot if I come in with loads of shopping" automation to close the sunroof too :)

**Comment by P6g9YHK6** [comment]
would be nice as a 
no rain
outdoor temp < indoor
parked since 10min
open the vent 


close when rain or temp regulated

**Comment by P6g9YHK6** [comment]
Exemple automation:

```
alias: Tesla smart sunroof vent control
triggers:
  - entity_id:
      - sensor.elmo_fu_uwu_temperature_inside
      - sensor.elmo_fu_uwu_temperature_outside
      - weather.XXXXXXXX
    trigger: state
actions:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ valid_temps }}"
          - condition: template
            value_template: "{{ temp_good }}"
          - condition: template
            value_template: "{{ not raining_now }}"
          - condition: template
            value_template: "{{ not rain_forecast }}"
        sequence:
          - delay:
              minutes: 10
          - condition: template
            value_template: >
              {{ valid_temps and temp_good and not raining_now and not
              rain_forecast }}
          - target:
              entity_id: cover.elmo_fu_uwu_sunroof
            action: cover.open_cover
          - delay:
              minutes: 15
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ valid_temps }}"
          - condition: or
            conditions:
              - condition: template
                value_template: "{{ raining_now }}"
              - condition: template
                value_template: "{{ rain_forecast }}"
              - condition: template
                value_template: "{{ outside >= (inside - 0.5) }}"
        sequence:
          - target:
              entity_id: cover.elmo_fu_uwu_sunroof
            action: cover.close_cover
mode: restart
variables:
  inside_raw: "{{ states('sensor.elmo_fu_uwu_temperature_inside') }}"
  outside_raw: "{{ states('sensor.elmo_fu_uwu_temperature_outside') }}"
  weather_state: "{{ states('weather.XXXXXXXX') }}"
  valid_temps: |
    {{ inside_raw not in ['unknown','unavailable','none',''] and
       outside_raw not in ['unknown','unavailable','none',''] }}
  inside: "{{ inside_raw | float }}"
  outside: "{{ outside_raw | float }}"
  raining_now: |
    {{ weather_state in ['rainy','pouring','lightning-rainy','thunderstorm'] }}
  rain_forecast: >
    {% set fc =
    state_attr('weather.XXXXXXXXX','forecast') %}
    {% if fc is not iterable or fc is none %}
      false
    {% else %}
      {% set ns = namespace(rain=false) %}
      {% for f in fc[:3] %}
        {% set p = f.get('precipitation', None) %}
        {% set pp = f.get('precipitation_probability', None) %}
        {% if (p is not none and p|float > 0) or (pp is not none and pp|float > 60) %}
          {% set ns.rain = true %}
        {% endif %}
      {% endfor %}
      {{ ns.rain }}
    {% endif %}
  temp_good: "{{ outside < (inside - 0.5) }}"

```
