### ISSUE TITLE
V3 powerwall SOC and energy remaining drop to 0

### ISSUE THREAD

**Issue by purcell-lab** [alandtse/tesla#296]
## Version of the custom_component

3.0.0

## Describe the bug

Raising an issue here to highlight an upstream bug that powerwall remaining energy and battery % regularly drop to 0 and then back to their actual values.

![Screenshot_20221023-122435](https://user-images.githubusercontent.com/79175134/197370192-791f692c-8cef-4eef-b378-030d0a59d8c6.png)

The Tesla API is the one who is reporting this drop to 0 so it is an upstream issue.

Workarounds include using an available: statement in template sensors or some type of averaging template.

**Comment by purcell-lab** [comment]
This workaround doesn't handle the legitimate 0 case, but is better than the stock item.

```yaml
 - platform: template
  sensors:
    filtered_powerwall_soc:
      value_template: "{{states('sensor.home_energy_gateway_battery')}}"
      availability_template: "{{states('sensor.home_energy_gateway_battery')|int(0) != 0}}"
      unit_of_measurement: "%"

    filtered_powerwall_battery_remaining: 
      value_template: "{{ states('sensor.home_energy_gateway_battery_remaining') }}"
      availability_template: "{{states('sensor.home_energy_gateway_battery_remaining')|int(0) != 0}}"
      unit_of_measurement: Wh
```
