### ISSUE TITLE
Incorrect state trigger?

### ISSUE THREAD

**Issue by rzulian** [alandtse/tesla#308]
Different sensors (e.g number.[x]_charge_limit,  sensor.[x]_charger_power) are triggering on state change, but the state didn't change.

```
trigger:
  id: '0'
  idx: '0'
  alias: null
  platform: state
  entity_id: sensor.tesla_model_y_charger_power
  from_state:
    entity_id: sensor.tesla_model_y_charger_power
    state: '1'
    attributes:
      state_class: measurement
      charger_amps_request: 1
      charger_amps_actual: 2
      charger_volts: 229
      charger_phases: 2
      unit_of_measurement: kW
      attribution: Data provided by Tesla
      device_class: power
      friendly_name: Tesla Model Y Charger power
    last_changed: '2022-10-26T00:25:57.621194+00:00'
    last_updated: '2022-10-26T05:42:59.704794+00:00'
    context:
      id: 01GG9D1EBREANRFXM5GQ8J86HH
      parent_id: null
      user_id: null
  to_state:
    entity_id: sensor.tesla_model_y_charger_power
    state: '1'
    attributes:
      state_class: measurement
      charger_amps_request: 1
      charger_amps_actual: 2
      charger_volts: 228
      charger_phases: 2
      unit_of_measurement: kW
      attribution: Data provided by Tesla
      device_class: power
      friendly_name: Tesla Model Y Charger power
    last_changed: '2022-10-26T00:25:57.621194+00:00'
    last_updated: '2022-10-26T05:54:09.384390+00:00'
    context:
      id: 01GG9DNWB84CAYD9E8T5JDBFFB
      parent_id: null
      user_id: null
  for: null
  attribute: null
  description: state of sensor.tesla_model_y_charger_power
```
