### ISSUE TITLE
Adding total energy (kWh) sensor for solar related entities

### ISSUE THREAD

**Issue by luisiam** [alandtse/tesla#330]
Is it possible to add total energy consumption/production (kWh) sensors for all solar related entities? That will be great for implementing tesla solar into the energy dashboard. Even though it can be done with the existing Riemann sum integration, there are quite a lot of issues using that integration and it will throw off the statistics. It will be nice if this integration will provide the kWh reading directly.

**Comment by purcell-lab** [comment]
The relevant energy endpoints for implementation of this FR are located here:
https://tesla-api.timdorr.com/energy-products/energy/history

**Comment by nicholashead** [comment]
Came here to post a new bug about this- but this issue is probably the best fit rather than opening a new one. I’ve tried multiple ways to get the kWh matching what the Tesla app shows (per day/month) without success. I’m not sure what I’m doing wrong or maybe it’s just not even possible?

This is what I currently have:

```yaml 
  - platform: integration
    source: sensor.my_home_solar_power
    name: tesla_solarpanels_new_kwh
    unit_prefix: k
    round: 2
 ```

**Comment by luisiam** [comment]
I have tried all three integral method and `left` seems to be matching the app the closest but it is still off. Hopefully this integration will provide the kWh sensor directly in the future.

**Comment by nicholashead** [comment]
I have not yet tried this manual kWh method, but was maybe gonna try it tonight: https://community.home-assistant.io/t/convert-w-to-kwh/327007

**Comment by luisiam** [comment]
> I have not yet tried this manual kWh method, but was maybe gonna try it tonight: https://community.home-assistant.io/t/convert-w-to-kwh/327007

That's new to me. I will try and compare my current integral with `left` method.

**Comment by nicholashead** [comment]
I gave it a whirl but I must be doing something wrong. Sensors I added:

In sensor.yaml:

```yaml
  - platform: average  
    name: 'Tesla Solar Average Power'
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'
    entities: sensor.my_home_solar_power
  - platform: average
    name: 'Tesla Solar Five Minute Average Power'
    duration:
      minutes: 5
    entities: sensor.my_home_solar_power
```

```yaml
template:
  - sensor:
      - name: Tesla New KWH Sensor
        state: "{{ '%0.2f'|format(states('sensor.tesla_solar_average_power')|float / 1000 * (now().hour + now().minute/60)) }} "
        unit_of_measurement: "kWh"
        device_class: energy
        state_class: total_increasing
```

But the "Tesla New KWH Sensor" is pretty high- even higher than my original sensor:

```yaml
  - platform: integration
    source: sensor.my_home_solar_power
    name: tesla_solarpanels_new_kwh
    unit_prefix: k
    round: 2
```

**Comment by luisiam** [comment]
My setup as follows and it is very close to the `integration` sensor. Remember always use `method: left` in the `integration` sensor.

This is my `average` power sensor setup
```yaml
sensor:
  # Average Solar Power
  - platform: average
    name: Average Solar Power
    start: "{{ today_at('00:00') }}"
    end: "{{ now() }}"
    entities: sensor.my_home_solar_power
```

This is my `template` energy sensor setup
```yaml
template:
  - sensor:
      # Daily Solar Energy
      - name: Daily Solar Energy
        device_class: energy
        state_class: total_increasing
        state: "{{ (float(states('sensor.average_solar_power'), default = 0.0) * ((now() - today_at('00:00')).total_seconds() / 3600) / 1000) | round(2) }}"
        unit_of_measurement: kWh
```

This is my original `integration` energy sensor
```yaml
sensor:
  - platform: integration
    source: sensor.my_home_solar_power
    name: Solar Energy
    round: 4
    unit_prefix: k
    method: left
```

Both sensors yield 27.1kWh and the Tesla app shows 27.4kWh of solar production yesterday. However, I was having a perfect sunny day and that was the perfect scenario without any spike in the solar power. I will keep monitoring both sensors and pick the one getting me result closer to the Tesla app.
