### ISSUE TITLE
Destination tracker status is 'home' all the time - seems not usable for triggering

### ISSUE THREAD

**Issue by anhaff** [alandtse/tesla#455]
V3.8.0 according to my HACS - seems to be the latest

Tried to trigger an automation while being away from home with the newly added destination tracker:

![image](https://user-images.githubusercontent.com/88614880/208968353-1290991d-f35f-4c27-af9f-0b6fc2e70ed7.png)

I simply activated navigation to home while some km away. It never triggered. Destination tracker showed status 'home' wherever I was - at home, not at home, navigating to home, not navigating at all (cancelled navigation while away)

Or did I do something wrong?

Shouldn't the state of the entity preferably be something like 'arrived', 'not_navigating' and/or similar?

**Comment by InTheDaylight14** [comment]
Hmm, the sensor holds onto the last destination. In the current version I think you would have to set the navigation away from home so that the destination location changes. Then when coming back you navigate home and the state would change from "not_home" to "Home" and trigger the automation. 

This brings up a good edge case. The solution that comes to mind is making the location "Unknown" when not navigating. This would drop the destination from the map and guarantees that navigating Home is always triggered. 

> Shouldn't the state of the entity preferably be something like 'arrived', 'not_navigating' and/or similar?

The device_tracker state will follow the name of setup zones. So if you had a Work zone setup it's possible to know the car is navigating to Work.

**Comment by InTheDaylight14** [comment]
> Hmm, the sensor holds onto the last destination.

Okay, reviewing the code. This is not the case. The Tesla API still responds with the ```active_route_latitude``` even after reaching the destination. Looks like that location will not change until a new destination is selected and it updates. 

When writing the code I had expected the Tesla API to drop the active route information if not actively navigating. That would have taken the destination off the map. A solution is not coming to mind right now besides navigating away from Home and then to Home.

**Comment by carleeno** [comment]
@anhaff you can use the distance to arrival sensor as the trigger (set from: unknown so it doesn't repeat).

```
alias: Detect heading home via Mystique
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.mystique_distance_to_arrival
    from: unknown
condition:
  - condition: state
    entity_id: device_tracker.mystique_destination_location_tracker
    state: home
action:
  - service: script.heading_home
    data: {}
mode: single
```
