### ISSUE TITLE
charger_phases incorrectly showing 2 phases on 3-phase charger

### ISSUE THREAD

**Issue by hakong** [alandtse/tesla#493]
<img width="788" alt="image" src="https://user-images.githubusercontent.com/4422113/213888900-af73ce61-d40e-4601-a2fc-ef90cedb5fca.png">
It should be 3 phases.

Running v3.9.1

Not sure what other info to attach.

**Comment by alandtse** [comment]
We're reporting what Tesla is reporting. You can try looking at teslajsonpy logs to see what data is there. If it's wrong, you need to talk to Tesla.

**Comment by hakong** [comment]
Ok, thanks. I turned on debug logging in HA but it doesn't print enough info to show what's going on.
Teslamate is showing the correct number of phases:
![image](https://user-images.githubusercontent.com/4422113/214973577-c50ad63b-5cc0-467d-bf62-670e2be4549e.png)

**Comment by purcell-lab** [comment]
This is what Tesla are reporting from upstream.

Here is my work around.

```yaml
    ev_phases:
      friendly_name: "EV Charger Phases (adjusted)"
      value_template: "{{ max(1,(state_attr('sensor.duka_charger_power','charger_phases')|int(0)*3/2)|int(0))}}"
```
