### ISSUE TITLE
FR: Set charge limit

### ISSUE THREAD

**Issue by remulasce** [alandtse/tesla#52]
Expose https://www.teslaapi.io/vehicles/commands#set-charge-limit

I'm trying to limit how much my car is allowed to charge at home, since I only have inefficient 120v home charging and time of use restrictions. However, I still want to allow home charging up to a certain safety amount (say 40%), rather than always enabling or disabling charging at home.

I could do fancy things like poll the current charge state and use the enable/disable charging switch, but it's a lot more complicated compared to the API which does exactly this, and it also runs into potential problems with the car going to sleep and the charge state not necessarily being available.

Thanks

**Comment by alandtse** [comment]
This is something that has been [discussed in the api](https://github.com/zabuldon/teslajsonpy/issues/59). The problem is how to display it in HA.

**Comment by remulasce** [comment]
It seems like HA has example code for using a 'light' to control what is really a volume knob in https://www.home-assistant.io/integrations/light.template/#theater-volume-control.

What is the 'custom service call' thing that is discussed in that issue? It seems a little backwards to give access only to the API surface that conveniently maps to existing toggles. Is there a different way I can call Tesla's API from Home Assistant without needing these UI base types?

**Comment by drobtravels** [comment]
If anyone's looking for some templates to make this easier... I made this script to set the charge limit to any value

```yaml
script:
  set_tesla_max_charge:
    description:  Set Tesla Max Charge
    fields:
      charge_limit:
        name: charge_limit
        description: Max Percent of charge
        required: true
        example: 70
        default: 70
    mode: queued
    sequence:
      - service: tesla_custom.api
        data:
          email: !secret tesla_user
          command: CHANGE_CHARGE_LIMIT
          parameters:
            path_vars:
              vehicle_id: !secret tesla_vehicle_id
            wake_if_asleep: true
            percent: '{{ charge_limit}}'
```

And a custom "max range" switch which uses my preferred values.  Note that I use teslamate MQTT to get all state instead of this component.  You will like need to edit the `value_template` and `availability_template` properties.

```yaml

switch:
  - platform: template
    switches:
      tesla_trip_charge:
        friendly_name: Tesla Charge for Road Trip
        unique_id: chase_trip_charge_293u439
        availability_template: "{{ is_number(states('sensor.teslamate_charge_limit_soc')) }}"
        value_template: "{{ states('sensor.teslamate_charge_limit_soc')|int  >= 90 }}"
        turn_on:
          service: script.set_tesla_max_charge
          data:
            charge_limit: 96
        turn_off:
          service: script.set_tesla_max_charge
          data:
            charge_limit: 70
```
