### ISSUE TITLE
Powerwall operation mode does not update from the cloud following HA restart

### ISSUE THREAD

**Issue by jaymunro** [alandtse/tesla#618]
## Version of the custom_component
3.12.2

## Configuration

From core.config_entries
```yaml
      {
        "entry_id": "<redacted>",
        "version": 1,
        "domain": "tesla_custom",
        "title": "<redacted>",
        "data": {
          "token": “<redacted>“,
          "access_token": "<redacted>",
          "expiration": 1685400615,
          "username": "<redacted>",
          "domain": "https://auth.tesla.com",
          "include_vehicles": true,
          "include_energysites": true,
          "initial_setup": false
        },
        "options": {},
        "pref_disable_new_entities": false,
        "pref_disable_polling": false,
        "source": "user",
        "unique_id": null,
        "disabled_by": null
      },
```

## Describe the bug
Following HA restart the OperationMode sensor is always empty 'unknown' and does not update from the cloud, even after many hours (tested up to 11 hours).

<img width="346" alt="Screenshot 2023-05-29 at 6 57 24 PM" src="https://github.com/alandtse/tesla/assets/1166024/bb1075b1-b4ae-46f2-ab4d-53479a46c4b3">
<img width="578" alt="Screenshot 2023-05-29 at 7 11 01 PM" src="https://github.com/alandtse/tesla/assets/1166024/27adf719-9f82-4b4e-94d7-6ec36c49c056">

## Debug log

Debug log attached below but the following may be relevant.

```text
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:560
First occurred: 6:11:47 PM (1 occurrences)
Last logged: 6:11:47 PM

Entity select.my_home_operation_mode (<class 'custom_components.tesla_custom.select.TeslaEnergyOperationMode'>) is using self.async_update_ha_state(), without enabling force_update. Instead it should use self.async_write_ha_state(), please report it to the custom integration author.


```
[home-assistant_tesla_custom_2023-05-29T06-46-22.585Z.log](https://github.com/alandtse/tesla/files/11589295/home-assistant_tesla_custom_2023-05-29T06-46-22.585Z.log)

**Comment by jaymunro** [comment]
Transferring this comment from #619 for reference:
This started May 27 at 4:12PM (NZST), just 2 days ago. Before that the sensor would populate correctly after a restart. Other powerwall tesla custom sensors are populating without issue.

**Comment by jaymunro** [comment]
Additionally, changes made to the setting in the official phone Tesla app do not propagate down to this custom_component.
Changes made in this custom_component **DO** propagate up to the cloud and are reflected in the official phone Tesla app.

**Comment by jaymunro** [comment]
Checking the time it is attempting to update the value against debug logs, I am seeing a "script error":
ERROR (MainThread) [frontend.is.latest.202305033] :0:0 Script error.

Working through this, I see other sensors updating with valid values at the same time, e.g. 'Grid charging'
<img width="536" alt="Screenshot 2023-06-01 at 4 54 02 PM" src="https://github.com/alandtse/tesla/assets/1166024/217df9af-108f-44a5-b8df-0c2250fbe563">

The sensor is updated from 'unavailable' to 'Yes' at 11:21:34

However for the 'Operation Mode' sensor, it is updated from 'unavailable' to 'unknown' at the same time, 11:21:34

<img width="897" alt="Screenshot 2023-06-01 at 4 52 01 PM" src="https://github.com/alandtse/tesla/assets/1166024/ac832a86-6ab8-4985-a67b-57319767957c">

**Comment by jaymunro** [comment]
@alandtse , I see the response in the debug logs does not return an operationhow does one use the HA service 'Tesla Custom Integration: api' ?
Specifically what does one put in each field? The following does not work and the links are not really helpful unless you're familiar with the process. The following results in `Failed to call service tesla_custom.api. Unknown error`
```
command: "SITE_SUMMARY"
```
```
parameters: {
    "AUTH": true,
    "TYPE": "GET",
    "URI": "api/1/energy_sites/11xxxxx0-14-J--CNxxxxxxxx4J03Y/site_status"
  }
```
Some of the ID is redacted above.

**Comment by jaymunro** [comment]
Looking at the code in `services.yaml', I found the following:
```
api:
  # Description of the service
  description: Run an API command using controller.api. https://teslajsonpy.readthedocs.io/en/latest/teslajsonpy/teslajsonpy.html#teslajsonpy.Controller.api
  # Different fields that your service accepts
  fields:
    # Key of the field
    email:
      # Description of the field
      description: Email address (optional if only one account)
      # Example value that can be passed for this field
      example: "elon@tesla.com"
      required: false
      selector:
        text:
    command:
      # Description of the field
      description: Command to run. See https://github.com/zabuldon/teslajsonpy/blob/master/teslajsonpy/endpoints.json
      # Example value that can be passed for this field
      example: "WAKE_UP"
      required: true
      selector:
        text:
    parameters:
      # Description of the field
      description: Parameters in a dictionary. `path_vars` replace variables in endpoints.json path. All others are passed directly to controller.api. For command parameters see https://tesla-api.timdorr.com/vehicle/commands.
      # Example value that can be passed for this field
      example: '{"path_vars": {"vehicle_id":"1"}, "wake_if_asleep":True}'
      required: true
      selector:
        object:
```

However, the `example:` does not show in the UI
<img width="1223" alt="Screenshot 2023-06-02 at 3 40 47 PM" src="https://github.com/alandtse/tesla/assets/1166024/60c931b4-afe5-4c04-852e-cf919b3aca2a">

But the above still produces the same error
