### ISSUE TITLE
Powerwall operation_mode does not update from the cloud following HA restart

### ISSUE THREAD

**Issue by jaymunro** [alandtse/tesla#619]
## Version of the custom_component
3.12.2

## Configuration

From core.config_entries
```yaml
      {
        "entry_id": "<redacted>",
        "version": 1,
        "domain": "tesla_custom",
        "title": "<redacted>",
        "data": {
          "token": “<redacted>“,
          "access_token": "<redacted>",
          "expiration": 1685400615,
          "username": "<redacted>",
          "domain": "https://auth.tesla.com",
          "include_vehicles": true,
          "include_energysites": true,
          "initial_setup": false
        },
        "options": {},
        "pref_disable_new_entities": false,
        "pref_disable_polling": false,
        "source": "user",
        "unique_id": null,
        "disabled_by": null
      },
```

## Describe the bug
Following HA restart the OperationMode sensor is always empty 'unknown' and does not update from the cloud, even after many hours (tested up to 11 hours).

<img width="346" alt="Screenshot 2023-05-29 at 6 57 24 PM" src="https://github.com/alandtse/tesla/assets/1166024/bb1075b1-b4ae-46f2-ab4d-53479a46c4b3">
<img width="578" alt="Screenshot 2023-05-29 at 7 11 01 PM" src="https://github.com/alandtse/tesla/assets/1166024/27adf719-9f82-4b4e-94d7-6ec36c49c056">

## Debug log

Debug log attached below but the following may be relevant.

```text
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:560
First occurred: 6:11:47 PM (1 occurrences)
Last logged: 6:11:47 PM

Entity select.my_home_operation_mode (<class 'custom_components.tesla_custom.select.TeslaEnergyOperationMode'>) is using self.async_update_ha_state(), without enabling force_update. Instead it should use self.async_write_ha_state(), please report it to the custom integration author.


```
[home-assistant_tesla_custom_2023-05-29T06-46-22.585Z.log](https://github.com/alandtse/tesla/files/11589295/home-assistant_tesla_custom_2023-05-29T06-46-22.585Z.log)
