### ISSUE TITLE
After upgrading to 1.1.1, getting "unknown error occured" when attempting to authenticate during re-setup 

### ISSUE THREAD

**Issue by deathstargunner** [alandtse/tesla#64]
## Configuration
```
## This configuration.yaml file is provided by the Home Assistant Core iocage-jail for TrueNAS Core
# Learn more at https://www.home-assistant.io/docs/configuration

homeassistant:
  # https://www.home-assistant.io/docs/configuration/customizing-devices/
  customize: !include customize.yaml
  # https://www.home-assistant.io/docs/configuration/packages/#create-a-packages-folder
  packages: !include_dir_named packages

http:
  # https://www.home-assistant.io/integrations/http/#ip_ban_enabled
  ip_ban_enabled: False
  login_attempts_threshold: 5

## Configure a default setup of Home Assistant Core (frontend, api, etc)
# Learn more at https://www.home-assistant.io/integrations/default_config
default_config:

# Text to speech
tts:
  - platform: google_translate

# Frontend
frontend:
  themes: !include_dir_merge_named themes
  
# Custom Work
media_player:
  - platform: yamaha
    host: 192.168.86.167
    source_names:
      HDMI1: "Apple TV"
      HDMI2: "Shield"
      HDMI3: "PS5"
      HDMI4: "Switch"
      HDMI5: "Blu-ray"
    zone_names:
      Main_Zone: "Living Room"
      Zone_2: "Patio"
      
sleepiq:
  username: !secret 
  password: !secret 

wake_on_lan:

samsungtv:
  - host: 192.168.86.62 
    turn_on_action:
      - service: wake_on_lan.send_magic_packet
        data:
          mac: BC:8C:CD:D8:FE:CB 
spotify:
  client_id: !secret 
  client_secret: !secret 

sensor:
  - platform: bitcoin
    display_options:
      - exchangerate
      - trade_volume_btc

#aarlo:
#  username: !secret
#  password: !secret arlo_password
#  refresh_devices_every: 2
#  stream_timeout: 120
#  tfa_source: push
#  tfa_type: PUSH

#alarm_control_panel:
#  - platform: aarlo
#    away_mode_name: armed
#    home_mode_name: Geofencing
#    night_mode_name: night
#    trigger_time: 30
#    alarm_volume: 8

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
light: !include lights.yaml
#tesla_cc: !include tesla.yaml

logger:
  default: info
  logs:
    hacs: debug
    custom_components.hacs: debug
    queueman: debug
    aiogithubapi: debug
```

## Describe the bug

Unable to set up "Tesla Custom Integration" via the Integrations, when adding email and refresh token error "Unknown Error Occurred" there is MFA on the account, but it worked fine prior to upgrading.  

## Debug log

```text

Add your logs here.

This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/tesla_custom/config_flow.py:160
Integration: tesla_custom (documentation, issues)
First occurred: 12:42:20 (3 occurrences)
Last logged: 12:43:18

Error handling request
Traceback (most recent call last):
  File "/usr/local/share/homeassistant/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/share/homeassistant/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/share/homeassistant/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/local/share/homeassistant/lib/python3.8/site-packages/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/local/share/homeassistant/lib/python3.8/site-packages/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware
    return await handler(request)
  File "/usr/local/share/homeassistant/lib/python3.8/site-packages/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/local/share/homeassistant/lib/python3.8/site-packages/homeassistant/components/http/auth.py", line 144, in auth_middleware
    return await handler(request)
  File "/usr/local/share/homeassistant/lib/python3.8/site-packages/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/local/share/homeassistant/lib/python3.8/site-packages/homeassistant/components/config/config_entries.py", line 157, in post
    return await super().post(request, flow_id)
  File "/usr/local/share/homeassistant/lib/python3.8/site-packages/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/local/share/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/data_entry_flow.py", line 111, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/local/share/homeassistant/lib/python3.8/site-packages/homeassistant/data_entry_flow.py", line 198, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/local/share/homeassistant/lib/python3.8/site-packages/homeassistant/data_entry_flow.py", line 256, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/home/homeassistant/homeassistant/custom_components/tesla_custom/config_flow.py", line 56, in async_step_user
    info = await validate_input(self.hass, user_input)
  File "/home/homeassistant/homeassistant/custom_components/tesla_custom/config_flow.py", line 160, in validate_input
    result = await controller.connect(test_login=True)
  File "/usr/local/share/homeassistant/lib/python3.8/site-packages/teslajsonpy/controller.py", line 349, in connect
    self.__energysite_name[energysite_id] = energysite["site_name"]
KeyError: 'site_name'
