### ISSUE TITLE
tesla_custom.api throws an UnknownError

### ISSUE THREAD

**Issue by jherby2k** [alandtse/tesla#72]
## Version of the custom_component

1.2.0

## Configuration

```yaml
service: tesla_custom.api
data:
  command: CHANGE_CLIMATE_TEMPERATURE_SETTING
  parameters:
    path_vars:
      vehicle_id: '786889216'
    driver_temp: 23.0
    passenger_temp: 23.0
    wake_if_asleep: true
```

or

```yaml
service: tesla_custom.api
data:
  command: REMOTE_SEAT_HEATER_REQUEST
  parameters:
    path_vars:
      vehicle_id: '786889216'
    heater: 1
    level: 1
    wake_if_asleep: true
```

## Describe the bug

Can't seem to get any tesla_custom.api service calls to work.

Both the above examples return an UnknownError immediately. I imagine i'm doing something wrong, but not sure what. I grabbed the vehicle_id from teslafi - it should always be the same, right?

> Logger: homeassistant.components.websocket_api.http.connection
> Source: custom_components/tesla_custom/services.py:89
> Integration: Home Assistant WebSocket API (documentation, issues)
> First occurred: 4:13:54 PM (3 occurrences)
> Last logged: 4:24:49 PM
> 
> [281473288586144] Error handling message: Unknown error
> 
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
>     await func(hass, connection, msg)
>   File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 525, in handle_execute_script
>     await script_obj.async_run(msg.get("variables"), context=context)
>   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1219, in async_run
>     await asyncio.shield(run.async_run())
>   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 353, in async_run
>     await self._async_step(log_exceptions=False)
>   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 371, in _async_step
>     await getattr(self, handler)()
>   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 571, in _async_call_service_step
>     await service_task
>   File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
>     task.result()
>   File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
>     await handler.job.target(service_call)
>   File "/config/custom_components/tesla_custom/services.py", line 43, in async_call_tesla_service
>     await api(service_call)
>   File "/config/custom_components/tesla_custom/services.py", line 89, in api
>     return await controller.api(name=command, path_vars=path_vars, **parameters)
>   File "/usr/local/lib/python3.9/site-packages/teslajsonpy/controller.py", line 166, in wake_up
>     result = await wrapped(*args, **kwargs)
>   File "/usr/local/lib/python3.9/site-packages/teslajsonpy/controller.py", line 1180, in api
>     return await self.__connection.post(
>   File "/usr/local/lib/python3.9/site-packages/teslajsonpy/connection.py", line 167, in post
>     return await self.__open(
>   File "/usr/local/lib/python3.9/site-packages/teslajsonpy/connection.py", line 218, in __open
>     raise TeslaException(resp.status_code)
> teslajsonpy.exceptions.TeslaException

**Comment by giachello** [comment]
in the debug section of homeassistan's configuration.yaml add `teslajsonpy: debug`

**Comment by InTheDaylight14** [comment]
Could the normal full response be made available as attributes of the location sensor? Or can that already be accessed elsewhere? That would make the vehicle_id available via attribute and we can use anything in the normal response cadence. Especially in templates. 

As an example use case, I have a cover template setup for opening and closing the windows. I'm using the latitude and longitude attributes of the location tracker in my api call to close the windows. 

```
cover:
  - platform: template
    covers:
      tesla_window:
        device_class: window
        friendly_name: "Tesla Window"
        # value_template: "{{ ? }}"
        open_cover:
          - service: tesla_custom.api
            data:
              command: WINDOW_CONTROL
              parameters:
                path_vars:
                  vehicle_id: 'my_id'
                command: vent
                lat: "{{state_attr('device_tracker.tesla_location_tracker','latitude') }}"
                long: "{{state_attr('device_tracker.tesla_location_tracker','longitude') }}"
                wake_if_asleep: true
        close_cover:
          - service: tesla_custom.api
            data:
              command: WINDOW_CONTROL
              parameters:
                path_vars:
                  vehicle_id: 'my_id'
                command: close
                lat: "{{state_attr('device_tracker.tesla_location_tracker','latitude') }}"
                long: "{{state_attr('device_tracker.tesla_location_tracker','longitude') }}"
                wake_if_asleep: true
```

If turned into an attribute, I think I could extract the current state of the windows from these in the normal response. Might be nice to have everything available. You never know what could be useful for edge cases. 
```
"vehicle_state":{
...
         "fd_window":0,
         "fp_window":0,
```

**Comment by alandtse** [comment]
> Could the normal full response be made available as attributes of the location sensor? Or can that already be accessed elsewhere?

I don't know what you're asking about with "normal full response". Service calls in HA cannot return data.

**Comment by jherby2k** [comment]
Awesome! Works great.

```yaml
service: tesla_custom.api
data:
  command: XXXX
  parameters:
    path_vars:
      vehicle_id: "{{ state_attr('binary_sensor.<car_name>_online_sensor', 'id') }}"
  foo: bar
```

... is going to be the standard template for just about every call, right? Would be cool if you could just do something like this instead:

```yaml
service: tesla_custom.api
data:
  command: XXXX
  car: <car_name>
  parameters:
    foo: bar
```

... but for what it is (a dev mode) this is wonderful. Thanks again!
