### ISSUE TITLE
Wall connector supported ?

### ISSUE THREAD

**Issue by pierrepinon** [alandtse/tesla#790]
Hello,

Wall connector is supported ? Because it's show on tesla api response, but no device was created for this entity

Thx for your reponse

**Comment by MindFreeze** [comment]
The VIN of the connected car is not exposed on the local API, so it would be very useful to have Wall connectors in this cloud integration as well

**Comment by Zappo-II** [comment]
FYI, this is what I do (your mileage may vary)...
```
template:
  - trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id:
        - binary_sensor.twc_vehicle_connected
      from: null
      to: 'on'
    - platform: state
      entity_id:
        - binary_sensor.twc_vehicle_connected
      from: null
      to: 'off'
      for:
        hours: 0
        minutes: 0
        seconds: 30
    - platform: state
      entity_id:
        - binary_sensor.twc_contactor_closed
      from: null
      to: 'off'
      for:
        hours: 0
        minutes: 0
        seconds: 30      
    - platform: state
      entity_id:
        - binary_sensor.twc_contactor_closed
      from: null
      to: 'on'
    action:
      - service: tesla_custom.api
        data:
          command: SITE_DATA
          parameters:
            path_vars:
              site_id: "myteslasiteid-put-yours-here"
        response_variable: MySiteData
    sensor:
      - name: TWC Current VIN
        unique_id: TWC_CurrentVIN
        icon: mdi:car-key
        state: |
          {% if MySiteData is defined -%}
            {% if MySiteData.response.wall_connectors[0].vin is defined -%}
              {% if MySiteData.response.wall_connectors[0].vin == "myvehicleid" -%}
                VIN: {{ MySiteData.response.wall_connectors[0].vin }} (myvehiclesname)
              {%- else -%}
                VIN: {{ MySiteData.response.wall_connectors[0].vin }} (Another unknown Tesla)
              {%- endif -%}
            {%- else -%}
              {% if MySiteData.response.wall_connectors[0].wall_connector_state == 2 -%}
                No VIN available (No Car Connected)
              {%- else -%}
                No VIN available (Unknown Car)
              {%- endif -%}
            {%- endif %}
          {%- else -%}
            No Data available
          {%- endif -%}
```

**Comment by Zappo-II** [comment]
BTW, to obtain `myteslasiteid-put-yours-here` call:

```
service: tesla_custom.api
data:
  command: PRODUCT_LIST
  parameters:
    path_vars:
      user_id: "1"
```

...and watch out for `energy_site_id:` in the response...
