### ISSUE TITLE
Close the windows on older Model S and X

### ISSUE THREAD

**Issue by Korte68** [alandtse/tesla#939]
**Is your feature request related to a problem? Please describe.**
By default the windows can not close remotely in case of older Model S/X.
**Describe the solution you'd like**
It would be great if we can close it.
Using the Tessie app, we can close, so the car can close the windows, just it is not published.
**Describe alternatives you've considered**

**Additional context**

**Comment by MarcelOudendijk** [comment]
Any news on this request?

I have the same issue.

**Comment by grodcur22** [comment]
I just figured out how to do it!!! 

Go to your **Scripts**, edit the YAML file, and paste this:

```yaml
alias: Cerrar Ventanas Tesla Pro
sequence:
  - service: tesla_custom.api
    data:
      command: WINDOW_CONTROL
      parameters:
        path_vars:
          vehicle_id: "{{ state_attr('binary_sensor.online', 'id') }}"
        command: close
        lat: "{{ state_attr('device_tracker.location_tracker', 'latitude') }}"
        lon: "{{ state_attr('device_tracker.location_tracker', 'longitude') }}"
        wake_if_asleep: true
mode: single
icon: mdi:window-maximize
```

---

## Step 2: Put it on your Dashboard

Add a **Button** or **Entity card** and choose your new script.

###  Pro Tip
You can use a **Button-type card** and in **"Action on touch"** choose:

- **Call service**
- Select your new script

Done! 


Or you can create an automation that triggers the script when you close the windows using the official button.
