### ISSUE TITLE
Dynamic Polling Automation not working

### ISSUE THREAD

**Issue by ddaddy** [alandtse/tesla#946]
I am setting up the Dynamic Polling as explained here: https://github.com/alandtse/tesla/wiki/Dynamic-Polling-Frequency

When I run the action of an automation to set it to 30s I see no difference.

What exactly is the binary_sensor referred to in these lines?
```
action:
    - delay: '00:01:00'
    - service: tesla_custom.polling_interval
      data:
        vin: "{{ state_attr('binary_sensor.' ~ trigger.entity_id.split('.')[1].split('_')[0] ~ '_online_sensor','vin') }}"
        scan_interval: 30
```

I have no sensor ending with `_online_sensor`. Has this perhaps been renamed?
I also have no entity called `tesla_custom.polling_interval`.

**Comment by ddaddy** [comment]
Ah ok. I guess the `_sensor` ending has been removed.

So I have this which seems to make the HA UI happy:
```
action:
  - delay: "00:01:00"
  - service: tesla_custom.polling_interval
    data:
      vin: binary_sensor.jess_online
      scan_interval: 30
```

**Comment by sgriessini** [comment]
You have to use the VIN attribute: _state_attr('binary_sensor.jess_online','vin')_

**Comment by ddaddy** [comment]
Ah yes, that makes sense now.
Is there any way to view the current polling interval? I don't see a `tesla_custom.polling_interval` anywhere in the UI.

**Comment by ddaddy** [comment]
> Ah ok. I guess the `_sensor` ending has been removed.
> 
> So I have this which seems to make the HA UI happy:
> 
> ```
> action:
>   - delay: "00:01:00"
>   - service: tesla_custom.polling_interval
>     data:
>       vin: binary_sensor.jess_online
>       scan_interval: 30
> ```

In case anyone else looks this up. This wasn't actually working as it needs to be written as"
```
  action:
    - service: tesla_custom.polling_interval
      data:
        vin: "{{ state_attr('binary_sensor.jess_online','vin') }}"
        scan_interval: 30
```

I would be good to have access to the polling interval through a sensor.
