### ISSUE TITLE
Battery Remaining Unavailable

### ISSUE THREAD

**Issue by DigitalCharon** [alandtse/tesla#998]
### Is there an existing issue for this?

- [X] I have searched both the existing open issues & recently closed issues and did not find a duplicate of this issue.

### Version of the Tesla component

v3.23.0

### Version of the Powerwall Gateway software

24.12.6 3cc46fb9

### Model

3

### Current Behavior

battery remaining is unavailable. 

### Expected Behavior

battery percentage shows up

### Debug logs

```true
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:914
integration: Sensor (documentation, issues)
First occurred: June 12, 2024 at 11:06:25 PM (5 occurrences)
Last logged: 10:46:49 AM

Error adding entity sensor.powerwall_battery_remaining for domain sensor with platform tesla_custom
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 914, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1355, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1000, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1126, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1061, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1006, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 543, in state
    value = self.native_value
            ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tesla_custom/sensor.py", line 445, in native_value
    return round(self._energysite.energy_left)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/teslajsonpy/energy.py", line 152, in energy_left
    return round (self._site_config.get("nameplate_energy") * self.percentage_charged / 100 )
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'
```

**Comment by Dr-ead** [comment]
Having a similar issue here: Since yesterday I did not get any data from my Model S and I cannot send anything to it. via HA. Possible that the connection to the Tesla servers seem to be interrupted? Anyone else having this issue? For me it looks similar to the API thing at the start of this year.

**Comment by portaldon** [comment]
I have had the same issue just now and performing the same fix here resolved it - perhaps this is a regression: https://github.com/alandtse/tesla/issues/919#issuecomment-2015548967

**Comment by vvuk** [comment]
Similar but subtly different issue. Lots of `Task exception was never retrieved` (might be nice if the integration catches internal exceptions and sets itself to an error state or similar?), but the traceback is:

```
...
home-assistant  |   File "/config/custom_components/tesla_custom/sensor.py", line 445, in native_value
home-assistant  |     return round(self._energysite.energy_left)
home-assistant  |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
home-assistant  |   File "/usr/local/lib/python3.12/site-packages/teslajsonpy/energy.py", line 152, in energy_left
home-assistant  |     return round (self._site_config.get("nameplate_energy") * self.percentage_charged / 100 )
home-assistant  |                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
home-assistant  | TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'
```

which I believe means that `nameplate_energy` is an `int`, and `percentage_charged` is `None` -- whereas in the initial post about this issue, it looked like it was `None` and `float`. Could be the exact same issue just different python version/impl reporting differently, but it's odd.

**Comment by DigitalCharon** [comment]
I ended up getting my integration working again by replacing
`return round (self._site_config.get("nameplate_energy") * self.percentage_charged / 100 )`
with
`return round (self._site_config.get("battery_count")*self._site_summary.get("percentage_charged")*13500/100)`

in the energy.py of my local copy of teslajsonpy.

**Comment by Kosta-Github** [comment]
Right, the `nameplate_energy` value is also missing for me in the `energy site` API payload.

I have a `PowerWall 3` with software version `24.44.2 a6ea90d1`. See also be bug report here: https://github.com/zabuldon/teslajsonpy/issues/342

When I comment out the inclusion of `TeslaEnergyBatteryRemaining` in `sensor.py`, the integration is working as expected: https://github.com/alandtse/tesla/blob/3760ff380d7370b0ee01947d2905b7097442ba0e/custom_components/tesla_custom/sensor.py#L96

**Comment by rogeriw** [comment]
is there a guide on how to have your own local copy of teslajsonpy?  I have the same issue with the integration failing as above. 
 I tried putting the .py files from the git repo into a folder custom_components/teslajsonpy however it seems to ignore them - possibly because unlike others in custom_components folder its missing a manifest.json file.

**Comment by Dave-Jones-1963** [comment]
> I ended up getting my integration working again by replacing `return round (self._site_config.get("nameplate_energy") * self.percentage_charged / 100 )` with `return round (self._site_config.get("battery_count")*self._site_summary.get("percentage_charged")*13500/100)`
> 
> in the energy.py of my local copy of teslajsonpy.

Please can someone tell me how to do this as the "fix" to comment out the line "entities.append(TeslaEnergyBatteryRemaining(energysite, coordinator)) " Does allow the other items to update but does NOT show the battery charge percentage which I really need!
I am running Installation method - Home Assistant OS
Core - 2025.6.3
Supervisor - 2025.06.1
Operating System - 15.2
Frontend - 20250531.4
Tesla Custom Integration 3.25.0

**Comment by Dave-Jones-1963** [comment]
> Right, the `nameplate_energy` value is also missing for me in the `energy site` API payload.
> 
> I have a `PowerWall 3` with software version `24.44.2 a6ea90d1`. See also be bug report here: [zabuldon/teslajsonpy#342](https://github.com/zabuldon/teslajsonpy/issues/342)
> 
> When I comment out the inclusion of `TeslaEnergyBatteryRemaining` in `sensor.py`, the integration is working as expected:
> 
> [tesla/custom_components/tesla_custom/sensor.py](https://github.com/alandtse/tesla/blob/3760ff380d7370b0ee01947d2905b7097442ba0e/custom_components/tesla_custom/sensor.py#L96)
> 
> Line 96 in [3760ff3](/alandtse/tesla/commit/3760ff380d7370b0ee01947d2905b7097442ba0e)
> 
>  entities.append(TeslaEnergyBatteryRemaining(energysite, coordinator))

This doesn't fix the Power remaining issue just allows the integration to update the other entities which is good! But doesn't solve my issue

**Comment by adregner** [comment]
The fixed version of `teslajsonpy` is in its github, but it hasn't been pushed to PyPI as a new released version and therefore this homeassistant tesla custom integration doesn't have an updated version to depend on.  I had been logging in over SSH to my homeassistant container every time it updates to patch the two lines that make up this bug until I realized this could be automated by homeassistant itself.

The usual disclaimers and warnings apply about running random shell commands in your homeassistant core container and the dangerous things they could break.

```yaml
# Put this in config/configuration.yaml

shell_command:
  patch_nameplate_energy: |-
    sed -i -r 's/\.get\("(nameplate_energy|percentage_charged)"\)/.get("\1", 0)/' /usr/local/lib/python3.13/site-packages/teslajsonpy/energy.py
```

```yaml
# This is the yaml description of the automation I setup in the UI

alias: Patch teslajsonpy on startup
triggers:
  - trigger: homeassistant
    event: start
conditions:
  - condition: or
    conditions:
      - condition: state
        entity_id: sensor.quartz_home_battery
        state: unknown
      - condition: state
        entity_id: sensor.quartz_home_battery
        state: unavailable
actions:
  - action: shell_command.patch_nameplate_energy
  - action: notify.mobile_app_andrew_iphone
    data:
      title: Homeassistant Reloaded
      message: teslajsonpy has been patched
  - action: homeassistant.restart
mode: single
```
